name: agent
version: "0.0.1"
slug: agent
description: agent
url: "https://github.com/evolvingconcepts/adn"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
image: "ghcr.io/evolvingconcepts/agent:agent-v0.0.2"